config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  devise_for :users
  resources :posts do
    resources :likes
  end

  root "pages#home"

  get 'user_posts/:user_id' => 'posts#user', as: :user_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  def handle
    self.email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected
  def after_sign_in_path_for(user)
    posts_url
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    post_id = params[:post_id]

    if !!current_user
      liked = Like.find_by(post_id: post_id, user_id: current_user.id)

      if !liked
        like = Like.create(post_id: post_id, user_id: current_user.id)
      else
        liked.destroy
      end

    end
    redirect_to posts_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
  end

  def create
    post = Post.create(message_params)
    redirect_to posts_url
  end

  def user
    @posts = Post.where(user_id: current_user.id).order(created_at: :desc)
  end

  private

  def message_params
    params[:post][:user_id] = current_user.id unless current_user == nil
    params.require(:post).permit(:title, :content, :image, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar_top">
  <% if user_signed_in? %>
    <div class="navbar_left">
      <%= link_to "All Photos", posts_path, :class => "nav_link" %>
      <%= link_to "Your Photos", user_posts_path( current_user.id ), :class => "nav_link"%>
    </div>

    <div class="navbar_right">
      <span class="navbar_text"><%= current_user.handle %></span>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "nav_link" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'navbar' %>
    <%= stylesheet_link_tag    'posts_index' %>
    <%= stylesheet_link_tag    'form' %>
    <%= stylesheet_link_tag    'homepage' %>

    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="top_level_container">
  <h1>Oh hi there, welcome to Instagram!</h1>

  <h2>Do you want to:</h2>
  <div class="homepage_container">
    <ul>
      <li><%= link_to new_user_registration_path do%>
          <p class="link_list">sign up</p>
        <% end %>
      </li>
      <li><%= link_to new_user_session_path do%>
          <p class="link_list">sign in</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/posts/_all_posts.html.erb
<div class="posts_flexbox">
  <% @posts.each do | post | %>
    <div class="post_container">
      <%= image_tag(post.image, class: "post_image") %>
      <p class="post_title"><%= post.title %></p>
      <% liked = Like.find_by(post_id: post.id, user_id: current_user.id) %>
      <%= link_to post_likes_path(post), method: :post, class: "link_to_like" do %>
        <% if !liked %>
          <%= 'Like' %>
        <% else %>
          <%= 'Unlike' %>
        <% end %>
      <% end %>
      <p id="number_likes" class="like_value_<%= post.id%>"><%=post.likes.count%></p>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<% if user_signed_in? %>
  <%= form_for Post.new do |form| %>
    <%= form.text_field :title, placeholder: 'photo title' %>
    <%= form.file_field :image %>
    <%= form.submit "Post", id: 'form_submit' %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<h2>Instagram</h2>

<%= render "form" %>

<%= render "all_posts" %>

app/views/posts/user.html.erb
<h3>Here are all your photos <%= %></h3>
<%= render "all_posts" %>